[package]
name = "rust_3d_sorting"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.17.3", default-features = false, features = [
  "bevy_asset",
  "bevy_audio",
  "bevy_camera",
  "bevy_color",
  "bevy_core_pipeline",
  "bevy_image",
  "bevy_log",
  "bevy_mesh",
  "bevy_pbr",
  "bevy_picking",
  "bevy_post_process",
  "bevy_render",
  "bevy_shader",
  "bevy_state",
  "bevy_winit",
  "mp3",
  "png",
  "symphonia-aac",
  "symphonia-flac",
  "symphonia-wav",
  "tonemapping_luts",
  "vorbis",
  "zstd_rust"
] }
bevy_egui = "0.38.1"
bevy_panorbit_camera = { version = "0.33.0" }
fastrand = { version = "2.3.0" }
log = { version = "*", features = ["max_level_debug", "release_max_level_warn"] }
regex-lite = "0.1.8"
rfd = "0.17.2"  # required in wasm as well: Error goes away: no method named `get` found for struct `FileList` in the current scope

[dev-dependencies]
bevy = { version = "0.17.3", default-features = false, features = ["debug"] }
bevy_egui = { version = "0.38.1", features = [
  "log_file_dnd_messages",
  "log_input_messages"
] }

[build-dependencies]
winresource = "0.1.30"  # just for windows

[target.'cfg(target_arch = "wasm32")'.dependencies]
bevy = { version = "0.17.3", default-features = false, features = [
  "web",
  "webgl2"
] }
console_error_panic_hook = "0.1.7"
fastrand = { version = "2.3.0", features = ["js"] }
futures = "0.3.31"
wasm-bindgen = "0.2.113"
wasm-bindgen-futures = "0.4.58"
web-sys = { version = "0.3.85", features = [
  "Document",
  "FileList",
  "HtmlDivElement",
  "HtmlInputElement",
  "Window"
] }

[target.'cfg(target_arch = "x86_64")'.dependencies]
bevy = { version = "0.17.3", default-features = false, features = [
  "bevy_window",
] }
image = "0.25.9"  # same as what bevy uses (used cargo tree to see which version bevy uses first)
winit = "0.30.12"  # same as what bevy uses

[profile.dev]
# Very little optimizations on dev builds for fastest compiles
# All these settings also apply to all dependencies unless overwritten: [profile.dev.packages."*"]
opt-level = 0
debug = false  # not using a debugger currently so no need to enable this
strip = false
lto = "off"
panic = "unwind"
codegen-units = 16

[profile.release]
opt-level = 3  # different from wasm: "z"
debug = false
strip = true  # different from wasm: "debuginfo": cannot strip for wasm compilation
lto = "fat"
panic = "abort"
codegen-units = 1

[profile.release-wasm32]
# used by trunk: trunk build --release --cargo-profile release-wasm32
inherits = "release"
opt-level = "z"  # different from x86 (opt-level = 3)
strip = "debuginfo"  # different from x86 (strip = true)
panic = "unwind"  # gives me smaller wasm than panic = "abort"
