trunk-version = "^0.21.14"  # Trunk version at the start of this project.
# Just remove above if you want to see if trunk can still build in a different version.

# https://trunk-rs.github.io/trunk/guide/configuration/index.html#build-section

[build]
target = "index.html"  # The index HTML file to drive the bundling process.
minify = "on_release"  # Control minification: can be one of: never, on_release, always
dist = "docs"  # The folder name can be used by GitHub Pages (if not using GitHub Actions)
public_url = "/"  # Where assets are placed on the website
