trunk-version = "^0.21.14"  # Trunk version at the start of this project.
# Just remove above if you want to see if trunk can still build in a different version.

# https://trunk-rs.github.io/trunk/guide/configuration/index.html#build-section

# Some of these options may be overwritten when building for release: (e.g., no file hashing) check "Trunk Build" in tasks.json
[build]
target = "index.html"  # The index HTML file to drive the bundling process.
dist = "docs"  # The folder name can be used by GitHub Pages (if not using GitHub Actions)
public_url = "/"  # Where assets are placed on the website
# minify = "on_release"  # never, on_release, always. Errors RequiredTokenNotFound(Identifier) [token=Some(KeywordDefault)] (due to unsupported wasm-bindgen ES6+ code?)
filehash = true  # file hashing
no_sri = true  # integrity checks disable
